// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
	"pznrestfulapi/app"
	"pznrestfulapi/controller"
	"pznrestfulapi/middleware"
	"pznrestfulapi/repository"
	"pznrestfulapi/service"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepositoryImpl := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := validator.New()
	categoryServiceImpl := service.NewCategoryService(categoryRepositoryImpl, db, validate)
	categoryControllerImpl := controller.NewCategoryController(categoryServiceImpl)
	authRepositoryImpl := repository.NewAuthRepository()
	authServiceImpl := service.NewAuthService(authRepositoryImpl, db, validate)
	authControllerImpl := controller.NewAuthController(authServiceImpl)
	router := app.NewRouter(categoryControllerImpl, authControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImpl)), service.NewCategoryService, wire.Bind(new(service.CategoryService), new(*service.CategoryServiceImpl)), controller.NewCategoryController, wire.Bind(new(controller.CategoryController), new(*controller.CategoryControllerImpl)))

var authSet = wire.NewSet(repository.NewAuthRepository, wire.Bind(new(repository.AuthRepository), new(*repository.AuthRepositoryImpl)), service.NewAuthService, wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)), controller.NewAuthController, wire.Bind(new(controller.AuthController), new(*controller.AuthControllerImpl)))
